spring:
  ldap:
    embedded:
      ldif: classpath:test-server.lidf

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: